clean_livingroom:
  sequence:
  - action: vacuum.send_command
    metadata: {}
    data:
      command: app_segment_clean
      params:
      - segments:
        - 18
        - 16
        - 17
        - 19
        repeat: 1
    target:
      entity_id: vacuum.helene_wischer
  alias: Clean Livingroom
  description: ''
  icon: mdi:sofa
