version: 4
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: addons
  password: #PASSWORD REMOVED
serial:
  port: /dev/ttyUSB0
  adapter: ember
advanced:
  log_level: info
  channel: 11
  network_key:
    - 56
    - 59
    - 72
    - 112
    - 145
    - 64
    - 123
    - 212
    - 111
    - 157
    - 76
    - 236
    - 7
    - 64
    - 152
    - 121
  pan_id: 42782
  ext_pan_id:
    - 24
    - 12
    - 129
    - 214
    - 188
    - 66
    - 164
    - 138
  transmit_power: 20
frontend:
  enabled: true
  port: 8099
homeassistant:
  enabled: true
devices:
  '0x000d6ffffe9dfabe':
    friendly_name: Ikea Tradfri Repeater
  '0xa4c13862122bb0ce':
    friendly_name: Fenster Bad
  '0x086bd7fffe1e9207':
    friendly_name: Tradfri Remote
  '0x000d6ffffea4e14b':
    friendly_name: Fyrtur Büro
    homeassistant:
      cover:
        position_closed: 5
  '0x00be44fffeab1c6d':
    friendly_name: Inspelning Treppe
    current_precision: ''
  '0x00be44fffeac6cb9':
    friendly_name: 'Inspelning Schlafzimmer '
  '0x00be44fffeab77d0':
    friendly_name: Inspelning Studio
  '0xa4c13865b0a12151':
    friendly_name: 'Fenster Waschraum '
  '0xa4c1386e064b44b4':
    friendly_name: Dachfenster
  '0x001788010981be29':
    friendly_name: Terrasse links
  '0x00178801098756a2':
    friendly_name: Terrasse rechts
  '0x001788010d2b4b73':
    friendly_name: 'Hue Dimmer Switch '
  '0xa4c1389b2a796503':
    friendly_name: Fenster Gast
groups:
  '1':
    friendly_name: Licht Terrasse
